spring:
   datasources:
      ds0:
         driverClassName: com.mysql.cj.jdbc.Driver
         type: com.alibaba.druid.pool.DruidDataSource
         url: jdbc:mysql://172.18.66.88:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
         username: root
         password: root123!        
         initial-size: 5
         min-idle: 5
         max-idle: 10
         max-active: 20
         max-wait: 60000
         time-between-eviction-runs-millis: 60000
         min-evictable-idle-time-millis: 300000
         validation-query: SELECT 1 FROM DUAL
         test-while-idle: true
         test-on-borrow: false
         test-on-return: false
         pool-prepared-statements: true
         max-pool-prepared-statement-per-connection-size: 20
         useGlobalDataSourceStat: true
         connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
         filter:
            commons-log:
               statement-log-enabled: true
               statement-executable-sql-log-enable: true
               
      ds1:
         driverClassName: com.mysql.cj.jdbc.Driver
         type: com.alibaba.druid.pool.DruidDataSource
         url: jdbc:mysql://172.18.66.88:3306/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
         username: root
         password: root123!        
         initial-size: 5
         min-idle: 5
         max-idle: 10
         max-active: 20
         max-wait: 60000
         time-between-eviction-runs-millis: 60000
         min-evictable-idle-time-millis: 300000
         validation-query: SELECT 1 FROM DUAL
         test-while-idle: true
         test-on-borrow: false
         test-on-return: false
         pool-prepared-statements: true
         max-pool-prepared-statement-per-connection-size: 20
         useGlobalDataSourceStat: true
         connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
         filter:
            commons-log:
               statement-log-enabled: true
               statement-executable-sql-log-enable: true
                 
mybatis:
  mapper-locations: mapper/*Mapper.xml      

propConfig:
   dsKeyPrefix: ds
   sharding: 2